extract = 'total_dyn_inst: (\d+)'
benchmarks = '../../bril/benchmarks/*/*.bril'

[runs.baseline]
pipeline = ["bril2json", "brili -p {args}"]

[runs.lvn]
pipeline = ["bril2json", "python3 lvn.py", "python3 dce.py", "brili -p {args}"]
