extract = 'total_dyn_inst: (\d+)'
benchmarks = '../../bril/benchmarks/**/*.bril'

[runs.baseline]
pipeline = ["bril2json", "brili -p {args}"]

[runs.dom]
pipeline = ["bril2json", "python3 dom.py dom", "brili -p {args}"]