extract = 'total_dyn_inst: (\d+)'
benchmarks = '../../bril/benchmarks/**/*.bril'

[runs.baseline]
pipeline = ["bril2json", "brili -p {args}"]

[runs.licm]
pipeline = ["bril2json", "python3 licm.py", "brili -p {args}"]
